/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class es_hol_chernyshov_parserdictionary_Parser */

#ifndef _Included_es_hol_chernyshov_parserdictionary_Parser
#define _Included_es_hol_chernyshov_parserdictionary_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     es_hol_chernyshov_parserdictionary_Parser
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_es_hol_chernyshov_parserdictionary_Parser_hello
        (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_es_hol_chernyshov_parserdictionary_Parser_saveData
        (JNIEnv *, jclass, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif